name: daily-save-wallpaper.yml
on:
  workflow_dispatch:
  # push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: code

    - name: Set up JDK 17
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run:  java -jar target/bing-wallpaper-jar-with-dependencies.jar

    - name: Commit files
      run: |
        git config --local user.email "tongjiann@gmail.com"
        git config --local user.name "ROBOT"
        git add .
        git commit -m "upload resources"

    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GIT_TOKEN }}
        branch: pr-branch
        force: "true"

    - name: Create Pull Request
      id: cpr
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: 'update resources',
            owner,
            repo,
            head: 'pr-branch',
            base: 'main',
            body: [
              'This PR is auto-generated by',
              '[actions/github-script](https://github.com/actions/github-script).'
            ].join('\n')
          });
          github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['automerge']
          });
          return result.data.number
    - id: automerge
      name: automerge
      uses: "pascalgn/automerge-action@v0.16.3"
      env:
          GITHUB_TOKEN: "${{ secrets.MY_GIT_TOKEN }}"
          MERGE_DELETE_BRANCH: "true"
          PULL_REQUEST: ${{ steps.cpr.outputs.result }}
